name: elni

services:
  shipper:
    image: docker.elastic.co/beats/filebeat:7.17.3
    restart: always
    labels:
      - family=infrastructure
    environment:
      - ES_HOSTS=[elasticsearch:9200]
    user: root
    volumes:
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '500M'