filebeat.inputs:
- type: container
  paths: 
    - '/var/lib/docker/containers/*/*.log'

processors:
- add_docker_metadata:
    host: "unix:///var/run/docker.sock"

- decode_json_fields:
    fields: ["message"]
    target: "" # means set to root doc
    overwrite_keys: true

output.elasticsearch:
  hosts: ${ES_HOSTS}
  indices:
    - index: "logs-%{[container.labels.family]}-%{[container.name]}-%{+yyyy.MM.dd}"
    - index: "logs-nofamily-%{[container.name]}-%{+yyyy.MM.dd}"