version: "3.9"

networks:
  elastic_net:
    driver: bridge

volumes:
  esdata:

services:
  elasticsearch:
    labels:
      - family=infrastructure
    image: elasticsearch:7.17.3 # the highest version that just works
    restart: always
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - esdata:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '500M'

  kibana:
    restart: always
    labels:
      - family=infrastructure
    image: kibana:7.17.3
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '500M'

  filebeat:
    restart: always
    labels:
      - family=infrastructure
    build:
      dockerfile: filebeat.Dockerfile
      context: .
    image: vosarat/elni-filebeat:1.0
    user: root
    volumes:
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '500M'

  elnik-webapi:
    restart: always
    image: vosarat/elni-webapi:1.0
    labels:
      - family=nist
    build:
      context: .
      dockerfile: Elnik.WebApi/Dockerfile
    environment:
      - KIBANA_URL=http://kibana:5601
    ports:
      - "5610:80"
  
  elnik-service:
    restart: always
    image: vosarat/elni-service:1.0
    labels:
      - family=background
    build:
      context: .
      dockerfile: Elnik.Background.Service/Dockerfile
    environment:
      - ELNIK_URL=http://elnik-webapi