@host = http://localhost:5074

###
GET /query-controller?name=Egor&age=29

###
GET /parameters-mini?name=Egor&age=29

###
GET /parameters-controller?name=Egor&age=29

###
GET /hard-parameters-mini?name=Egor&age=29&tags=tag1,tag2&time=2020-02-20T12%3A16%3A00.0000000Z

###
GET /dict-parameters-mini?labels.system=sysa&labels.app=appa