name: elni

services:
  shipper:
    image: vosarat/el-shippy
    restart: always
    build: .
    labels:
      - family=infrastructure
    environment:
      - ES_HOSTS=[elasticsearch:9200]
      - PREFIX=cool-logs
    user: root
    volumes:
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '500M'