{{nist-example}}/about

###
{{nist-example}}/greetings/Egor?name=Alex

###
{{nist-example}}/greetings/government?name=Falex

###
PATCH {{nist-example}}/greetings

{
    "addressee" : "Brian"
}

###
PATCH {{nist-example}}/greetings

{
    "addressee" : "government"
}

###
GET {{nist-example}}/farewells?name=Joshua

###
GET {{nist-example}}/farewells?name=dream

###
POST {{nist-example}}/companies/aldar/office