@pendingDashboard = {{GET_dashboards.response.body.$.pending[0]}}

@existingDashboard = {{GET_dashboards.response.body.$.existing[0]}}

@pendingIndexes = {{GET_indexes.response.body.$.pending[0]}}

@existingIndexes = {{GET_indexes.response.body.$.existing[0]}}

###
# @name GET_dashboards
GET http://localhost:5610/dashboards

###
PUT http://localhost:5610/dashboards/{{pendingDashboard}}

###
# @name GET_indexes
GET http://localhost:5610/indexes

###
POST http://localhost:5610/indexes

"{{pendingIndexes}}"

### Just in case delete methods
###
DELETE http://localhost:5610/dashboards/nisters

###
DELETE http://localhost:5610/indexes/logs-*