volumes:
  esdata:

services:
  elasticsearch:
    labels:
      - family=infrastructure
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    restart: always
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - esdata:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1GB'

  kibana:
    restart: always
    labels:
      - family=infrastructure
    image: docker.elastic.co/kibana/kibana:8.14.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '500M'