###
GET /transactions

###
GET /transactions?limit=2&include=total

###
GET /transactions?limit=0&include=categories.total,categories.totalSum

###
GET /transactions?limit=2&include=total,categories.total,categories.totalSum