name: Build & Push Elni WebApi Image

on:
  push:
    paths:
      - 'tools/elni/Elnik.WebApi/**'
      - '.github/workflows/docker-elni-webapi.yaml'

  workflow_dispatch:

jobs:
  push-image:
    name: Build & Push image
    runs-on: ubuntu-latest
    steps:
      - uses: astorDev/versy/calver/docker@main
        with:
          image: 'vosarat/elni-webapi'
          build-context-path: 'tools/elni'
          dockerfile-path: 'tools/elni/Elnik.WebApi/Dockerfile'
          docker-login: 'vosarat'
          docker-password: ${{ secrets.DOCKER_PASSWORD }}