name: Publish Nist.Logs
on:
  push:
    paths:
      - 'dotnet/logging/lib/**'
      - '.github/workflows/nuget-logs.yml'

jobs:
  publish:
    name: Pack & Publish nuget
    runs-on: ubuntu-latest
    steps:
      - uses: astorDev/versy/calver/nuget@main
        with:
          project: dotnet/logging/lib/Nist.Logs
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}