name: Nist.Webhooks.Dump Nuget
on:
  push:
    paths:
      - 'webhooks/accept/lib/**'
      - '.github/workflows/nuget-webhooks-dump.yaml'
  workflow_dispatch:

jobs:
  publish:
    name: Pack & Publish nuget
    runs-on: ubuntu-latest
    steps:
      - uses: astorDev/versy/calver/nuget@main
        with:
          project: webhooks/accept/lib/Nist.Webhooks.Dump
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}