name: Publish Nist.Queries
on:
  push:
    paths:
      - 'dotnet/queries/Nist.Queries/**'
      - '.github/workflows/nuget-queries.yaml'
  workflow_dispatch:

jobs:
  publish:
    name: Pack & Publish nuget
    runs-on: ubuntu-latest
    steps:
      - uses: astorDev/versy/calver/nuget@main
        with:
          project: dotnet/queries/Nist.Queries/Nist.Queries
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}