name: Publish Nist.Logs
on:
  push:
    paths:
      - 'logging/dotnet/io/lib/**'
      - '.github/workflows/nuget-logs.yaml'
  workflow_dispatch:

jobs:
  publish:
    name: Pack & Publish nuget
    runs-on: ubuntu-latest
    steps:
      - uses: astorDev/versy/calver/nuget@main
        with:
          project: logging/dotnet/io/lib/Nist.Logs
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}