name: Publish Nist.Logs
on:
  push:
    paths:
      - 'dotnet/bodies/lib/**'
      - '.github/workflows/nuget-bodies.yaml'
  workflow_dispatch:

jobs:
  publish:
    name: Pack & Publish nuget
    runs-on: ubuntu-latest
    steps:
      - uses: astorDev/versy/calver/nuget@main
        with:
          project: dotnet/bodies/lib/Nist.Bodies
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}