name: Publish Nist.Responses

on:
  push:
      
jobs:
  publish:

    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v3
      - run: | 
          cd dotnet/responses
          ls
          export VERSION=$(date +'%Y.1%m.1%d')
          echo $VERSION