name: Publish Nist.Errors
on:
  push:
    paths:
      - 'errors/lib/**'
      - '.github/workflows/nuget-errors.yaml'
  workflow_dispatch:

jobs:
  publish:
    name: Pack & Publish nuget
    runs-on: ubuntu-latest
    steps:
      - uses: astorDev/versy/calver/nuget@main
        with:
          project: errors/lib/Nist.Errors
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}