name: Publish Nist.Proxy
on:
  push:
    paths:
      - 'proxy/dotnet/lib/**'
      - '.github/workflows/proxy-nuget.yaml'
  workflow_dispatch:

jobs:
  publish:
    name: Pack & Publish nuget
    runs-on: ubuntu-latest
    steps:
      - uses: astorDev/versy/calver/nuget@main
        with:
          project: proxy/lib/Nist.Proxy
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}